### ISSUE TITLE
TYPO3 9.5 class aliases are not applied

### ISSUE THREAD

**Issue by DanielSiepmann** [sabbelasichon/typo3-rector#2467]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.20             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ebd3efa-db7c-6d08-bff8-6733382b731a

## Expected Behaviour

I would expect that `TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper` is adjusted to `TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper`

I'll try to debug the issue and add further comments with outcome.

**Comment by DanielSiepmann** [comment]
It looks like the `configure()` method of `src/Rector/Migrations/RenameClassMapAliasRector.php` is called as expected.
But `refactor()` is never called.

So probably `getNodeTypes()` misses some type? But I can't find a list of available types and what they represent. There is also no PHPDoc within the source code of those types. So I'm stuck there.

**Comment by sabbelasichon** [comment]
This should be fixed with version 0.11.32 and above.

**Comment by DanielSiepmann** [comment]
I'm on 0.11.32: `rector/rector                              0.11.32`
I still receive an error:
```
 [ERROR] Analyze error: "Class TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper not found.". Include your files in
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration
```

The https://github.com/sabbelasichon/typo3-rector/blob/main/docs/best_practice_guide.md mentions some `ClassAliasMap` I should provide, but doesn't mention where to get that file or how to provide the file.

**Comment by ayacoo** [comment]
@DanielSiepmann Have you tried this with the dev-main of rector/rector? I changed my code to check and it changed the class.

An include is missing for the "extbase" 9.5 folder, I'll add it right away.

**Comment by sabbelasichon** [comment]
@ayacoo Could you also create a PR for the documentation so we can close this issue here. Would be very helpful for everyone else when skipping one major version during upgrade

**Comment by ayacoo** [comment]
@sabbelasichon That's how it worked for me after the bug fix. Do you mean the doc update for composer.json regarding ClassAliasMap? If so, I would be happy to add it.

**Comment by sabbelasichon** [comment]
Exactly. That's not well documented but should be

**Comment by ayacoo** [comment]
Addendum: I was able to recreate the problem from Daniel with myself and it ran through with Sebastian's following solution. My latest hint referred to the ObjectManager and not the class loading via the class header. I will take care of a documentation  PR at the weekend.

composer.json -> extra Section

```

"typo3/class-alias-loader": {
   "class-alias-maps": [
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/adminpanel/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/backend/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/core/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/extbase/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/fluid/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/info/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/lowlevel/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/recordlist/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/reports/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/t3editor/Migrations/Code/ClassAliasMap.php",
      "vendor/rector/rector/vendor/ssch/typo3-rector/Migrations/TYPO3/9.5/typo3/sysext/workspaces/Migrations/Code/ClassAliasMap.php"
   ]
},
```

**Comment by sabbelasichon** [comment]
Resolved by #2539

**Comment by DanielSiepmann** [comment]
Added the PR for docs, thanks @ayacoo for the concrete example. Worked as expected and solved my issues :) Used it for the docs PR.
